name: CI

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # debug action - you ca connect with ssh
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v2

    # setup nativescript
    - name: Setup nativescirpt
      uses: andreav/setup-nativescript-action@master
      with:
        platform: 'ubuntu'  
