name: CI

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build_adroid:    
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Extract secret, android firebase cfg file
    - name: Extract google-services.json
      run: 'echo "$GOOGLE_SERVICES_JSON" > app/App_Resources/Android/google-services.json'
      shell: bash
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

    # setup nativJescript
    - name: Setup nativescirpt
      uses: andreav/setup-nativescript-action@master
      with:
        platform: 'ubuntu'  

    - name: Build Android Package
      run: tns build android

    # debug action - you ca connect with ssh
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v2

  build_ios:    
    runs-on: macos-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Extract secret, android firebase cfg file
    - name: Extract GoogleService-Info.plist
      run: 'echo "$GOOGLE_SERVICES_INFO_PLIST" > app/App_Resources/iOS/GoogleService-Info.plist'
      shell: bash
      env:
        GOOGLE_SERVICES_INFO_PLIST: ${{ secrets.GOOGLE_SERVICES_INFO_PLIST }}

    # debug action - you ca connect with ssh
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2

    # setup nativJescript
    - name: Setup nativescirpt
      uses: andreav/setup-nativescript-action@master
      with:
        platform: 'macos'  

    - name: Build IOS Package
      run: tns build ios

